name: Snyk Security Test and Monitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Test for Vulnerabilities
        run: snyk test --all-projects --reachable
        continue-on-error: true

      - name: Monitor Project in Snyk
        run: snyk monitor --all-projects --reachable
        continue-on-error: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image with Labels
        id: build_docker
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Generated Image Tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.revision=$COMMIT_SHA" \
            --label "org.opencontainers.image.version=$IMAGE_TAG" \
            --label "org.opencontainers.image.branch=$GIT_BRANCH" \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$IMAGE_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}

      - name: Monitor Docker Image in Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Monitoring Docker Image in Snyk with commit: $COMMIT_SHA and branch: $GIT_BRANCH"
          snyk monitor --docker ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }} \
            --project-name=my-app-${{ github.repository }}-$GIT_BRANCH-$COMMIT_SHA
