name: Snyk Security Test and Monitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Debug Logs
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Log Environment Variables
        run: |
          echo "GITHUB_JOB=${GITHUB_JOB}"
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}"
          echo "RUNNER_OS=${RUNNER_OS}"

      - name: Build Docker Image with Unique Tag
        id: build_docker
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "Generated Image Tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$IMAGE_TAG .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}

      - name: Monitor Docker Image in Snyk with Metadata
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_JOB: ${{ env.GITHUB_JOB }}
          GITHUB_REF: ${{ env.GITHUB_REF }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_RUN_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
          RUNNER_OS: ${{ env.RUNNER_OS }}
        run: |
          echo "Monitoring Docker Image in Snyk with tag: ${{ steps.build_docker.outputs.IMAGE_TAG }}"
          docker run --rm -e "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" \
          -e "GITHUB_JOB=${{ env.GITHUB_JOB }}" \
          -e "GITHUB_REF=${{ env.GITHUB_REF }}" \
          -e "GITHUB_SHA=${{ env.GITHUB_SHA }}" \
          -e "GITHUB_REPOSITORY=${{ env.GITHUB_REPOSITORY }}" \
          -e "GITHUB_RUN_NUMBER=${{ env.GITHUB_RUN_NUMBER }}" \
          -e "RUNNER_OS=${{ env.RUNNER_OS }}" \
          -v "/var/run/docker.sock:/var/run/docker.sock" \
          snyk/snyk:docker snyk monitor --docker ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }} --severity-threshold=critical --target-reference="main"
