name: Snyk Security Test and Monitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Echo Environment Variables
        run: |
          echo "GITHUB_JOB=$GITHUB_JOB"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_WORKFLOW=$GITHUB_WORKFLOW"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"

      - name: Run Snyk as a Docker Container
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_JOB: ${{ github.job }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_ACTOR: ${{ github.actor }}
          RUNNER_OS: ${{ runner.os }}
          RUNNER_TEMP: ${{ runner.temp }}
          RUNNER_WORKSPACE: ${{ runner.workspace }}
        run: |
          docker run --rm \
            --name snyksnykdocker_be2cdb \
            --workdir /github/workspace \
            -e SNYK_TOKEN \
            -e GITHUB_JOB \
            -e GITHUB_REF \
            -e GITHUB_SHA \
            -e GITHUB_REPOSITORY \
            -e GITHUB_REPOSITORY_OWNER \
            -e GITHUB_WORKFLOW \
            -e GITHUB_ACTOR \
            -e RUNNER_OS \
            -e RUNNER_TEMP \
            -e RUNNER_WORKSPACE \
            -e GITHUB_ACTIONS=true \
            -e CI=true \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            -v "/home/runner/work/_temp/_github_home:/github/home" \
            -v "/home/runner/work/_temp/_github_workflow:/github/workflow" \
            -v "/home/runner/work/_temp/_runner_file_commands:/github/file_commands" \
            -v "/home/runner/work/p2p-fe-webview/p2p-fe-webview:/github/workspace" \
            snyk/snyk:docker snyk monitor --severity-threshold=critical --docker "${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}" --project-name=my-app-$GITHUB_SHA
