name: Snyk Security Test and Monitor with Full Environment Metadata

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Print Environment Variables
        run: env

      - name: Log Environment Variables for Snyk Docker Integration
        run: |
          echo "Environment Variables:"
          echo "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}"
          echo "GITHUB_JOB=${{ github.job }}"
          echo "GITHUB_RUN_ID=${{ github.run_id }}"
          echo "GITHUB_REF=${{ github.ref }}"
          echo "GITHUB_SHA=${{ github.sha }}"
          echo "GITHUB_REPOSITORY=${{ github.repository }}"
          echo "GITHUB_ACTOR=${{ github.actor }}"
          echo "RUNNER_OS=${{ runner.os }}"
          echo "RUNNER_ARCH=${{ runner.arch }}"
          echo "CI=${{ env.CI }}"
        env:
          CI: true

      - name: Build Docker Image with Unique Tag
        id: build_docker
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "Generated Image Tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$IMAGE_TAG .

      - name: Monitor Docker Image with Snyk in Container
        run: |
          echo "Starting Snyk Docker scan with metadata"
          docker run --rm \
            -e "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" \
            -e "GITHUB_JOB=${{ github.job }}" \
            -e "GITHUB_REF=${{ github.ref }}" \
            -e "GITHUB_SHA=${{ github.sha }}" \
            -e "GITHUB_REPOSITORY=${{ github.repository }}" \
            -e "GITHUB_ACTOR=${{ github.actor }}" \
            -e "RUNNER_OS=${{ runner.os }}" \
            -e "RUNNER_ARCH=${{ runner.arch }}" \
            -e "CI=true" \
            snyk/snyk:docker snyk monitor --docker ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }} --severity-threshold=high --project-name=my-app \
            --target-reference=${{ github.sha }}
