name: Snyk Security Test and Monitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image with Unique Tag
        id: build_docker
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "Generated Image Tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$IMAGE_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}
          echo "Docker image pushed: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}"

      - name: Debug Image Tag
        run: |
          echo "Image tag used: ${{ steps.build_docker.outputs.IMAGE_TAG }}"

      - name: Monitor Docker Image in Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}"
          echo "Monitoring Docker Image in Snyk with commit: $COMMIT_SHA and image: $IMAGE"
          
          # Run Snyk as a Docker container
          docker run --rm \
            -e SNYK_TOKEN="${{ secrets.SNYK_TOKEN }}" \
            -e GITHUB_JOB="${{ github.job }}" \
            -e GITHUB_REF="${{ github.ref }}" \
            -e GITHUB_SHA="${{ github.sha }}" \
            -e GITHUB_REPOSITORY="${{ github.repository }}" \
            -e GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}" \
            -e GITHUB_RUN_ID="${{ github.run_id }}" \
            -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
            -e GITHUB_WORKFLOW="${{ github.workflow }}" \
            -e RUNNER_OS="${{ runner.os }}" \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            snyk/snyk:docker snyk monitor --docker "$IMAGE" --project-name=my-app-$COMMIT_SHA
