name: Snyk Security Test and Monitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Test for Vulnerabilities
        run: snyk test --all-projects --reachable
        continue-on-error: true

      - name: Monitor Project in Snyk
        run: snyk monitor --all-projects --reachable
        continue-on-error: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image with Labels
        id: build_docker
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Generated Image Tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.revision=$COMMIT_SHA" \
            --label "org.opencontainers.image.version=$IMAGE_TAG" \
            --label "org.opencontainers.image.branch=$GIT_BRANCH" \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:$IMAGE_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}

      - name: Monitor Docker Image in Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Monitoring Docker Image in Snyk with commit: $COMMIT_SHA and branch: $GIT_BRANCH"
          /usr/bin/docker run --name snyksnykdocker_be2cdb --rm \
            --label 0c629d \
            --workdir /github/workspace \
            -e "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" \
            -e "INPUT_IMAGE" \
            -e "INPUT_ARGS" \
            -e "INPUT_COMMAND" \
            -e "INPUT_JSON" \
            -e "INPUT_SARIF" \
            -e "SNYK_INTEGRATION_NAME" \
            -e "SNYK_INTEGRATION_VERSION" \
            -e "HOME" \
            -e "GITHUB_JOB" \
            -e "GITHUB_REF" \
            -e "GITHUB_SHA" \
            -e "GITHUB_REPOSITORY" \
            -e "GITHUB_REPOSITORY_OWNER" \
            -e "GITHUB_REPOSITORY_OWNER_ID" \
            -e "GITHUB_RUN_ID" \
            -e "GITHUB_RUN_NUMBER" \
            -e "GITHUB_RETENTION_DAYS" \
            -e "GITHUB_RUN_ATTEMPT" \
            -e "GITHUB_REPOSITORY_ID" \
            -e "GITHUB_ACTOR_ID" \
            -e "GITHUB_ACTOR" \
            -e "GITHUB_TRIGGERING_ACTOR" \
            -e "GITHUB_WORKFLOW" \
            -e "GITHUB_HEAD_REF" \
            -e "GITHUB_BASE_REF" \
            -e "GITHUB_EVENT_NAME" \
            -e "GITHUB_SERVER_URL" \
            -e "GITHUB_API_URL" \
            -e "GITHUB_GRAPHQL_URL" \
            -e "GITHUB_REF_NAME" \
            -e "GITHUB_REF_PROTECTED" \
            -e "GITHUB_REF_TYPE" \
            -e "GITHUB_WORKFLOW_REF" \
            -e "GITHUB_WORKFLOW_SHA" \
            -e "GITHUB_WORKSPACE" \
            -e "GITHUB_ACTION" \
            -e "GITHUB_EVENT_PATH" \
            -e "GITHUB_ACTION_REPOSITORY" \
            -e "GITHUB_ACTION_REF" \
            -e "GITHUB_PATH" \
            -e "GITHUB_ENV" \
            -e "GITHUB_STEP_SUMMARY" \
            -e "GITHUB_STATE" \
            -e "GITHUB_OUTPUT" \
            -e "RUNNER_OS" \
            -e "RUNNER_ARCH" \
            -e "RUNNER_NAME" \
            -e "RUNNER_ENVIRONMENT" \
            -e "RUNNER_TOOL_CACHE" \
            -e "RUNNER_TEMP" \
            -e "RUNNER_WORKSPACE" \
            -e "ACTIONS_RUNTIME_URL" \
            -e "ACTIONS_RUNTIME_TOKEN" \
            -e "ACTIONS_CACHE_URL" \
            -e "ACTIONS_RESULTS_URL" \
            -e GITHUB_ACTIONS=true \
            -e CI=true \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            -v "/home/runner/work/_temp/_github_home:/github/home" \
            -v "/home/runner/work/_temp/_github_workflow:/github/workflow" \
            -v "/home/runner/work/_temp/_runner_file_commands:/github/file_commands" \
            -v "/home/runner/work/p2p-fe-webview/p2p-fe-webview:/github/workspace" \
            snyk/snyk:docker snyk monitor --severity-threshold=critical --target-reference=master --docker ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ steps.build_docker.outputs.IMAGE_TAG }}
